### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ctrlcmdshft** [MiguelRAvila/Bento#1]
where can we source the icons you are using? Is there a site we can goto to see other icons to use that match. 

Thanks

**Comment by MiguelRAvila** [comment]
@ctrlcmdshft  I made the icons myself based on the https://feathericons.com/ Feather icons. I can share with you the Figma I used to design the rest and change the colors. https://www.figma.com/file/VZPK9j6QQLaeVHsBGaHAHs/Bento-Icons?node-id=0%3A1

**Comment by ctrlcmdshft** [comment]
Great thanks! also is there a way to change from 24hr time and also celsius to fahrenheit?

**Comment by MiguelRAvila** [comment]
@ctrlcmdshft Both are made with Javascript. About Celsius to Fahrentheit, the API gives the temperature in Kelvin, you can use the formula here  `weather.temperature.value = Math.floor(data.main.temp - KELVIN);`
