### ISSUE TITLE
How do I open the link in the same tab ? 

### ISSUE THREAD

**Issue by groovitz** [MiguelRAvila/Bento#13]
I use your Simplerent fox userChrome and I love it. It's just elegant and nice. So I decided to use your Bento startpage. I have added a couple links and added the weather and it has been great so far. Just a question though. How do I open the links in the same tab? Your doc says that target="blank" opens the link in a new tab. I don't know html so I looked at how to open the link in the same tab, and it said that you have to put target="_self" instead. So I tried it and it still opens the links in a new tab. 
What do I do?

**Comment by MiguelRAvila** [comment]
Hey! @groovitz to open it in the same tab you must remove all the `target="xxx"` property.

**Comment by groovitz** [comment]
![2020-12-21-130352_1920x1080_scrot](https://user-images.githubusercontent.com/56974811/102751109-1bc0c500-438d-11eb-8320-75b95052a454.png)
When i comment out all target="blank" this happens
It works when I put _self instead of blank but firefox says that embedded links to websites cannot be opened in the same tab. :(

**Comment by MiguelRAvila** [comment]
Hmm I think that you should delete `target="blank"` not comment it, because you're also commenting the rest of your `<a>`. And yeah, Firefox does that :((( I also have that problem.

**Comment by groovitz** [comment]
Ah, alright. I'll close the issue then. Thanks for the cool new tab page. Keep it up.
