### ISSUE TITLE
Suggestion - Adding background images from the web

### ISSUE THREAD

**Issue by cjgsaunders** [MiguelRAvila/Bento#15]
Hello. First github post. Love the start page. I wanted to have a background image that dynamically changes each time the page is loaded. I added the code to my fork and was pleased with the results. Feel free to use it or not. Perhaps it detracts from the minimalist vibe. 

I used unsplash to randomly select the images. It offers keyword search for multiple keywords and resolution options. 

`4k example
 --imgbg: url(https://source.unsplash.com/featured/3840x2160/?{night},{animal});`
1080p example
`--imgbg: url(https://source.unsplash.com/featured/1920x1080/?{night});`    

and then add one line into body to blur it
`backdrop-filter: blur(10px);`

**note to add: firefox doesn't natively support backdrop-filter and needs to be enabled in about:config.
every other browser does

![dark3](https://user-images.githubusercontent.com/54923165/103264062-e8191700-49ec-11eb-8e13-5293e4bc815e.png)
![light](https://user-images.githubusercontent.com/54923165/103264071-f1a27f00-49ec-11eb-8dfc-3569f54c1236.png)

**Comment by MiguelRAvila** [comment]
Awesome job there! @cjgsaunders 
I'll thin about adding this or not. More because of the minimalist look the project aims. But I'll totally keep this code you've added to use it in the future!
