### ISSUE TITLE
breakpoints not displaying text correctly

### ISSUE THREAD

**Issue by cjgsaunders** [MiguelRAvila/Bento#16]
I noticed some strange behaviour when resizing the window. The breakpoints were not displaying the text correctly. 
See the screenshot for an example.
![breakpoint](https://user-images.githubusercontent.com/54923165/103266535-287b9380-49f3-11eb-9705-7f049a769a9a.png)

Probably not the best way of dealing with it but I addressed it by resizing the initial fonts (fsg and fsm) like this.
/* Fonts  */
    --fsg: 100px;    /* time and greeting */
    --fsm: 70px;    /* month+date */
    --fss: 30px;    /* greeting+weather*/
    --fses: 18px;   /* links */

result was this 
![break4](https://user-images.githubusercontent.com/54923165/103266788-b8b9d880-49f3-11eb-9143-2d0aa94b3e72.png)

Thanks for the project :)

.

**Comment by MiguelRAvila** [comment]
Hey! @cjgsaunders I'll check it and add the commets you put on your css in order to be more clear with that and everyone can tweek it even easier!
