### ISSUE TITLE
if statement logic issue

### ISSUE THREAD

**Issue by Kailash-777** [MiguelRAvila/Bento#18]
In greeting.js file, you have given the statement hour >= 23 and < 5. This statement will fail for 0, 1, 2, 3 and 4 since 0, 1, 2, 3 and 4 cannot be >= 23 AND < 5. It will also fail for 23 itself since 23 is not less than 5. This straight away goes to the else statement. Correct me if I am wrong.

**Comment by MiguelRAvila** [comment]
Hey @Kailash-777 You're right! I'll check out
