### ISSUE TITLE
Name is not changing from John Doe

### ISSUE THREAD

**Issue by AysenJ** [MiguelRAvila/Bento#21]
I have gone through and made all of the changes you left inside the guide and changed the respective figures and names to match what I need but the the name still does not update from John Doe to my name. Also, I cannot seem to get the day/night cycle to work correctly although that is my secondary worry. My main issue has to do with my name and the greetings.

**Comment by MiguelRAvila** [comment]
Hey @AysenJ  Have you commited and pull those changes into your repository?

**Comment by MiguelRAvila** [comment]
@AysenJ  I've checked your repo and you must put those files in the same directory you get them in order to change the content

**Comment by AysenJ** [comment]
I'm sorry, I am so new to all of this and I have no idea what you mean. Explain further. tbh, I switched from Bento to tabliss because it was easer although I would still use Bento it was working how I wanted it, and the way you intended it to

**Comment by MiguelRAvila** [comment]
I think I'll add a file or more instructions  to clarify everything you're experiencing. But I was referring that you must let the files in the same directories you found them.  That's why the links and greetings are not working @AysenJ
