### ISSUE TITLE
Custom Wallpaper not working

### ISSUE THREAD

**Issue by puntillol59** [MiguelRAvila/Bento#9]
I can see through the CSS code that the wallpaper section is un-commented:

![image](https://user-images.githubusercontent.com/62703475/100888739-6df48180-3484-11eb-92fa-4b87e946a0c2.png)

And the page does not show it:

![image](https://user-images.githubusercontent.com/62703475/100888842-88c6f600-3484-11eb-9511-c3bd6e750f13.png)

**Comment by puntillol59** [comment]
Actually, closing. The website just needed some time to update.

**Comment by MiguelRAvila** [comment]
Hey! @puntillol59  Don't worry! Nice to see you solve it!
